# Use the official HTTPD image from the Docker Hub
FROM httpd:alpine

# Copy the static HTML file to the HTTPD web root
COPY app/index.html /usr/local/apache2/htdocs/index.html

# Expose port 80 for the web server
EXPOSE 80

